name: Build Docker image
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout 
        uses: actions/checkout@v3
        with:
          submodules: recursive
      -
        name: Set variables
        id: vars
        run: |
          echo "IMAGE_TAG=v0.$(date '+%y%m%d%H%M%S')-$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
      -
        name: Generate Dockerfile
        run: |
          ./build.sh
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: ./
          file: ./Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/common-base-for-text:latest,${{ secrets.DOCKER_HUB_USERNAME }}/common-base-for-text:${{ steps.vars.outputs.IMAGE_TAG }}