name: Build Docker image
on:
  push:
    branches:
      - main
jobs:
  variables:
    runs-on: ubuntu-latest
    outputs:
      IMAGE_TAG: ${{ steps.vars.outputs.IMAGE_TAG }}
    steps:
      -
        name: Checkout 
        uses: actions/checkout@v3
        with:
          submodules: recursive
      -
        name: Set variables
        id: vars
        run: |
          echo "IMAGE_TAG=v0.$(date '+%y%m%d%H%M%S')-$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
  build-arm64:
    runs-on: ubuntu-latest
    needs: variables
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: arm64
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Checkout 
        uses: actions/checkout@v3
        with:
          submodules: recursive
      -
        name: Generate Dockerfile
        run: |
          ./build.sh
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      -
        name: Build and push slim
        uses: docker/build-push-action@v6
        with:
          context: ./
          file: ./Dockerfile
          push: true
          platforms: linux/arm64
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/common-base-for-text:latest,${{ secrets.DOCKER_HUB_USERNAME }}/common-base-for-text:${{ needs.variables.outputs.IMAGE_TAG }}-arm64
  build-amd64:
    runs-on: ubuntu-latest
    needs: variables
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Checkout 
        uses: actions/checkout@v3
        with:
          submodules: recursive
      -
        name: Generate Dockerfile
        run: |
          ./build.sh
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      -
        name: Build and push slim
        uses: docker/build-push-action@v6
        with:
          context: ./
          file: ./Dockerfile
          push: true
          platforms: linux/amd64
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/common-base-for-text:latest,${{ secrets.DOCKER_HUB_USERNAME }}/common-base-for-text:${{ needs.variables.outputs.IMAGE_TAG }}-amd64
  push-manifest:
    runs-on: ubuntu-latest
    needs: [variables, build-arm64, build-amd64]
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      -
        name: Create and push manifest
        run: |
          docker manifest create ${{ secrets.DOCKER_HUB_USERNAME }}/common-base-for-text:${{ needs.variables.outputs.IMAGE_TAG }} ${{ secrets.DOCKER_HUB_USERNAME }}/common-base-for-text:${{ needs.variables.outputs.IMAGE_TAG }}-arm64 ${{ secrets.DOCKER_HUB_USERNAME }}/common-base-for-text:${{ needs.variables.outputs.IMAGE_TAG }}-amd64
          docker manifest push ${{ secrets.DOCKER_HUB_USERNAME }}/common-base-for-text:${{ needs.variables.outputs.IMAGE_TAG }}
        
      # -
      #   name: Build and push full
      #   uses: docker/build-push-action@v6
      #   with:
      #     context: ./
      #     file: ./Dockerfile-full
      #     push: true
      #     platforms: linux/amd64,linux/arm64
      #     tags: ${{ secrets.DOCKER_HUB_USERNAME }}/common-base-for-text:latest,${{ secrets.DOCKER_HUB_USERNAME }}/common-base-for-text:${{ steps.vars.outputs.IMAGE_TAG }}-full
